export const approvedTokens = [
  '--ncai-font-family-sans',
  '--ncai-color-bg-canvas',
  '--ncai-color-bg-surface',
  '--ncai-color-bg-subtle',
  '--ncai-color-bg-disabled',
  '--ncai-color-text-primary',
  '--ncai-color-text-secondary',
  '--ncai-color-text-placeholder',
  '--ncai-color-text-inverse',
  '--ncai-color-text-danger',
  '--ncai-color-border-default',
  '--ncai-color-border-muted',
  '--ncai-color-border-hover',
  '--ncai-color-border-focus',
  '--ncai-color-border-danger',
  '--ncai-color-accent-primary',
  '--ncai-color-accent-primary-hover',
  '--ncai-color-accent-danger',
  '--ncai-radius-xs',
  '--ncai-radius-checkbox',
  '--ncai-radius-sm',
  '--ncai-radius-md',
  '--ncai-radius-full',
  '--ncai-space-1',
  '--ncai-space-2',
  '--ncai-space-3',
  '--ncai-space-4',
  '--ncai-space-5',
  '--ncai-font-size-caption',
  '--ncai-line-height-caption',
  '--ncai-font-size-label-sm',
  '--ncai-line-height-label-sm',
  '--ncai-font-size-label-md',
  '--ncai-line-height-label-md',
  '--ncai-font-size-label-lg',
  '--ncai-line-height-label-lg',
  '--ncai-duration-fast',
  '--ncai-duration-normal',
  '--ncai-ease-standard'
] as const;

export type ApprovedToken = (typeof approvedTokens)[number];
